// Generated by gencpp from file my_robot_msgs/SetLedPanelRequest.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MSGS_MESSAGE_SETLEDPANELREQUEST_H
#define MY_ROBOT_MSGS_MESSAGE_SETLEDPANELREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_robot_msgs
{
template <class ContainerAllocator>
struct SetLedPanelRequest_
{
  typedef SetLedPanelRequest_<ContainerAllocator> Type;

  SetLedPanelRequest_()
    : led_number(0)
    , led_state(false)  {
    }
  SetLedPanelRequest_(const ContainerAllocator& _alloc)
    : led_number(0)
    , led_state(false)  {
  (void)_alloc;
    }



   typedef int64_t _led_number_type;
  _led_number_type led_number;

   typedef uint8_t _led_state_type;
  _led_state_type led_state;





  typedef boost::shared_ptr< ::my_robot_msgs::SetLedPanelRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot_msgs::SetLedPanelRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetLedPanelRequest_

typedef ::my_robot_msgs::SetLedPanelRequest_<std::allocator<void> > SetLedPanelRequest;

typedef boost::shared_ptr< ::my_robot_msgs::SetLedPanelRequest > SetLedPanelRequestPtr;
typedef boost::shared_ptr< ::my_robot_msgs::SetLedPanelRequest const> SetLedPanelRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot_msgs::SetLedPanelRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot_msgs::SetLedPanelRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_robot_msgs::SetLedPanelRequest_<ContainerAllocator1> & lhs, const ::my_robot_msgs::SetLedPanelRequest_<ContainerAllocator2> & rhs)
{
  return lhs.led_number == rhs.led_number &&
    lhs.led_state == rhs.led_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_robot_msgs::SetLedPanelRequest_<ContainerAllocator1> & lhs, const ::my_robot_msgs::SetLedPanelRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::SetLedPanelRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::SetLedPanelRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::SetLedPanelRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::SetLedPanelRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::SetLedPanelRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::SetLedPanelRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot_msgs::SetLedPanelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1a9ef4af5785f2ab9471599c434f6a92";
  }

  static const char* value(const ::my_robot_msgs::SetLedPanelRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1a9ef4af5785f2abULL;
  static const uint64_t static_value2 = 0x9471599c434f6a92ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot_msgs::SetLedPanelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot_msgs/SetLedPanelRequest";
  }

  static const char* value(const ::my_robot_msgs::SetLedPanelRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot_msgs::SetLedPanelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 led_number\n"
"bool led_state\n"
;
  }

  static const char* value(const ::my_robot_msgs::SetLedPanelRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot_msgs::SetLedPanelRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.led_number);
      stream.next(m.led_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetLedPanelRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot_msgs::SetLedPanelRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot_msgs::SetLedPanelRequest_<ContainerAllocator>& v)
  {
    s << indent << "led_number: ";
    Printer<int64_t>::stream(s, indent + "  ", v.led_number);
    s << indent << "led_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.led_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_MSGS_MESSAGE_SETLEDPANELREQUEST_H
