// Generated by gencpp from file my_robot_msgs/SetLedPanel.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MSGS_MESSAGE_SETLEDPANEL_H
#define MY_ROBOT_MSGS_MESSAGE_SETLEDPANEL_H

#include <ros/service_traits.h>


#include <my_robot_msgs/SetLedPanelRequest.h>
#include <my_robot_msgs/SetLedPanelResponse.h>


namespace my_robot_msgs
{

struct SetLedPanel
{

typedef SetLedPanelRequest Request;
typedef SetLedPanelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetLedPanel
} // namespace my_robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_robot_msgs::SetLedPanel > {
  static const char* value()
  {
    return "ca637c0799ee071ea5139620f452c21c";
  }

  static const char* value(const ::my_robot_msgs::SetLedPanel&) { return value(); }
};

template<>
struct DataType< ::my_robot_msgs::SetLedPanel > {
  static const char* value()
  {
    return "my_robot_msgs/SetLedPanel";
  }

  static const char* value(const ::my_robot_msgs::SetLedPanel&) { return value(); }
};


// service_traits::MD5Sum< ::my_robot_msgs::SetLedPanelRequest> should match
// service_traits::MD5Sum< ::my_robot_msgs::SetLedPanel >
template<>
struct MD5Sum< ::my_robot_msgs::SetLedPanelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_robot_msgs::SetLedPanel >::value();
  }
  static const char* value(const ::my_robot_msgs::SetLedPanelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_robot_msgs::SetLedPanelRequest> should match
// service_traits::DataType< ::my_robot_msgs::SetLedPanel >
template<>
struct DataType< ::my_robot_msgs::SetLedPanelRequest>
{
  static const char* value()
  {
    return DataType< ::my_robot_msgs::SetLedPanel >::value();
  }
  static const char* value(const ::my_robot_msgs::SetLedPanelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_robot_msgs::SetLedPanelResponse> should match
// service_traits::MD5Sum< ::my_robot_msgs::SetLedPanel >
template<>
struct MD5Sum< ::my_robot_msgs::SetLedPanelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_robot_msgs::SetLedPanel >::value();
  }
  static const char* value(const ::my_robot_msgs::SetLedPanelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_robot_msgs::SetLedPanelResponse> should match
// service_traits::DataType< ::my_robot_msgs::SetLedPanel >
template<>
struct DataType< ::my_robot_msgs::SetLedPanelResponse>
{
  static const char* value()
  {
    return DataType< ::my_robot_msgs::SetLedPanel >::value();
  }
  static const char* value(const ::my_robot_msgs::SetLedPanelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_ROBOT_MSGS_MESSAGE_SETLEDPANEL_H
